<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'template-about-us',
        'title' => 'About us',
        'fields' => [
            [
                'key' => 'template-about-us_tab-hero',
                'label' => 'Hero',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'template-about-us_hero-title',
                'name' => 'hero__title',
                'label' => 'Title',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_hero-description',
                'name' => 'hero__description',
                'label' => 'Description',
                'type' => 'textarea',
                'required' => 0,
            ],
            [
                'key' => 'template-about-us_hero-image',
                'name' => 'hero__bg_id',
                'label' => 'Background',
                'type' => 'image',
                'return_format' => 'id',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_tab-timeline',
                'label' => 'Timeline',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'template-about-us_timeline-pretitle',
                'name' => 'timeline__pretitle',
                'label' => 'Pretitle',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_timeline-title',
                'name' => 'timeline__title',
                'label' => 'Title',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_timeline-description',
                'name' => 'timeline__description',
                'label' => 'Description',
                'type' => 'wysiwyg',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_timeline-repeater',
                'label' => 'Repeater',
                'name' => 'timeline__repeater',
                'type' => 'repeater',
                'required' => 1,
                'layout' => 'table',
                'min' => 1,
                'max' => 0,
                'sub_fields' => [
                    [
                        'key' => 'template-about-us_timeline-repeater-pretitle',
                        'name' => 'pretitle',
                        'label' => 'Pretitle',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_timeline-repeater-title',
                        'name' => 'title',
                        'label' => 'Title',
                        'type' => 'text',
                        'required' => 0,
                    ],
                    [
                        'key' => 'template-about-us_timeline-repeater-description',
                        'name' => 'description',
                        'label' => 'Description',
                        'type' => 'textarea',
                        'required' => 0,
                    ],
                ],
            ],
            [
                'key' => 'template-about-us_tab-our-solution',
                'label' => 'Our Solution',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'template-about-us_our-solution_pretitle',
                'name' => 'our_solution__pretitle',
                'label' => 'Pretitle',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_our-solution_title',
                'name' => 'our_solution__title',
                'label' => 'Title',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_our-solution_description',
                'name' => 'our_solution__description',
                'label' => 'Description',
                'type' => 'wysiwyg',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_our-solution-repeater',
                'label' => 'Repeater',
                'name' => 'our_solution__repeater',
                'type' => 'repeater',
                'required' => 1,
                'layout' => 'table',
                'min' => 1,
                'max' => 3,
                'sub_fields' => [
                    [
                        'key' => 'template-about-us_our-solution-repeater_tab',
                        'name' => 'tab',
                        'label' => 'Tab',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_our-solution-repeater_title',
                        'name' => 'title',
                        'label' => 'Title',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_our-solution-repeater_description',
                        'name' => 'description',
                        'label' => 'Description',
                        'type' => 'wysiwyg',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_our-solution-repeater_image',
                        'name' => 'background_id',
                        'label' => 'Image',
                        'type' => 'image',
                        'return_format' => 'id',
                        'required' => 1,
                    ],
                ],
            ],
            [
                'key' => 'template-about-us_tab-remake',
                'label' => 'Remake',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'template-about-us_remake_pretitle',
                'name' => 'remake__pretitle',
                'label' => 'Pretitle',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_remake_title',
                'name' => 'remake__title',
                'label' => 'Title',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_remake_description',
                'name' => 'remake__description',
                'label' => 'Description',
                'type' => 'wysiwyg',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_remake_image',
                'name' => 'remake__image',
                'label' => 'Background',
                'type' => 'image',
                'return_format' => 'id',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_remake-repeater',
                'label' => 'Repeater',
                'name' => 'remake__repeater',
                'type' => 'repeater',
                'required' => 0,
                'layout' => 'table',
                'min' => 0,
                'max' => 0,
                'sub_fields' => [
                    [
                        'key' => 'template-about-us_remake-repeater-title',
                        'name' => 'title',
                        'label' => 'Title',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_remake-repeater-number',
                        'name' => 'number',
                        'label' => 'Number',
                        'type' => 'number',
                        'required' => 1,
                        'min' => 1,
                    ],
                    [
                        'key' => 'template-about-us_remake-repeater-description',
                        'name' => 'description',
                        'label' => 'Description',
                        'type' => 'textarea',
                        'new_lines' => 'br',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_remake-repeater-select',
                        'label' => 'Type',
                        'name' => 'type',
                        'type' => 'select',
                        'choices' => [],
                        'allow_null' => 0,
                        'multiple' => 0,
                        'required' => 1,
                        'ui' => 1,
                        'return_format' => 'value',
                        'ajax' => 0,
                    ],
                ],
            ],
            [
                'key' => 'template-about-us_tab-our-team',
                'label' => 'Our Team',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'template-about-us_our-team_pretitle',
                'name' => 'our_team__pretitle',
                'label' => 'Pretitle',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_our-team_title',
                'name' => 'our_team__title',
                'label' => 'Title',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_our-team_description',
                'name' => 'our_team__description',
                'label' => 'Description',
                'type' => 'wysiwyg',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_our-team-repeater',
                'label' => 'Repeater',
                'name' => 'our_team__repeater',
                'type' => 'repeater',
                'required' => 1,
                'layout' => 'table',
                'min' => 1,
                'max' => 0,
                'sub_fields' => [
                    [
                        'key' => 'template-about-us_our-team-repeater_image',
                        'name' => 'image_id',
                        'label' => 'Image',
                        'type' => 'image',
                        'return_format' => 'id',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_our-team-repeater_title',
                        'name' => 'title',
                        'label' => 'Title',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_our-team-repeater_position',
                        'name' => 'position',
                        'label' => 'Position',
                        'type' => 'text',
                        'required' => 0,
                    ],
                ],
            ],
            [
                'key' => 'template-about-us_tab-reviews',
                'label' => 'Reviews',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'template-about-us_reviews_image',
                'name' => 'reviews__bg_id',
                'label' => 'Background',
                'type' => 'image',
                'return_format' => 'id',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_reviews_pretitle',
                'name' => 'reviews__pretitle',
                'label' => 'Pretitle',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'template-about-us_reviews-repeater',
                'label' => 'Repeater',
                'name' => 'reviews__repeater',
                'type' => 'repeater',
                'required' => 1,
                'layout' => 'table',
                'min' => 1,
                'max' => 0,
                'sub_fields' => [
                    [
                        'key' => 'template-about-us_reviews-repeater_title',
                        'name' => 'title',
                        'label' => 'Title',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_reviews-repeater_description',
                        'name' => 'description',
                        'label' => 'Description',
                        'type' => 'wysiwyg',
                        'required' => 1,
                    ],
                    [
                        'key' => 'template-about-us_reviews-repeater_rating',
                        'name' => 'rating',
                        'label' => 'Rating',
                        'type' => 'number',
                        'required' => 1,
                        'min' => 1,
                        'max' => 5,
                    ],
                ],
            ],
        ],
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page_templates/about-us.php',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'label_placement' => 'top',
        'active' => true,
    ));

endif;