<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_user_fields',
        'title' => 'Поля автора',
        'fields' => array(
            array(
                'key' => 'field_author_full_name_en',
                'label' => 'Повне імя (EN)',
                'name' => 'author_full_name_en',
                'type' => 'text',
                'instructions' => 'Введіть повне ім\'я автора англійською (якщо порожньо, використовується Display Name)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_author_position_uk',
                'label' => 'Посада (UK)',
                'name' => 'author_position_uk',
                'type' => 'text',
                'instructions' => 'Введіть посаду автора українською (наприклад: Аналітик ринку)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_author_position_en',
                'label' => 'Посада (EN)',
                'name' => 'author_position_en',
                'type' => 'text',
                'instructions' => 'Введіть посаду автора англійською (наприклад: Market Analyst)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_author_linkedin',
                'label' => 'LinkedIn URL',
                'name' => 'author_linkedin',
                'type' => 'url',
                'instructions' => 'Посилання на профіль у LinkedIn',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://www.linkedin.com/in/username/',
            ),
            array(
                'key' => 'field_author_photo',
                'label' => 'Фото автора',
                'name' => 'author_photo',
                'type' => 'image',
                'instructions' => 'Завантажте фото автора (рекомендується квадратна форма)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
